version: "3.8"

services:
  server1:
    build:
      context: ./servers
      dockerfile: Dockerfile
    ports:
      - "8001:8001"
    command: ["8001"]
    
  server2:
    build:
      context: ./servers
      dockerfile: Dockerfile
    ports:
      - "8002:8002"
    command: ["8002"]

  server3:
    build:
      context: ./servers
      dockerfile: Dockerfile
    ports:
      - "8003:8003"
    command: ["8003"]

  loadbalancer:
    build:
      context: ./loadbalancer
      dockerfile: Dockerfile
    env_file: ".env"
    ports:
      - "8080:8080"
    depends_on:
      - server1
      - server2
      - server3

